### ISSUE TITLE
Make an iOS client

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic#1]
Hi @kellyp (cc @girtsf),

Kelly was kind enough to be interested in making the iOS client (woot!).  So I just made some notes on how the bluetooth API works.  These notes might also be handy for Girts' interest in making a protocol client across the serial port (or possibly instead make a python bluetooth client that uses the bluetooth API? people might really dig that):

https://github.com/meshtastic/Meshtastic-esp32/blob/master/docs/software/bluetooth-api.md#meshbluetoothservice

**Comment by garthvh** [comment]
In the App Store https://apps.apple.com/us/app/meshtastic/id1586432531
