### ISSUE TITLE
Disambiguate Chat Channels vs LoRa Channels

### ISSUE THREAD

**Issue by Garrisonsan** [meshtastic/Meshtastic#1016]
**Issue**
A common complaint I hear when describing Meshtastic and LoRa to people unfamiliar with the technologies is that the nomenclature of calling logical groups of chat settings "channels" & simultaneously calling LoRa RF frequencies "channels" creates unnecessary confusion by making the term ambiguous.

**Suggested Changes**
For every instance of "channel" where it refers to chat settings, I suggest changing the name to either "room" or "group". The general public is familiar with both terms as they relate to the logical/topical organization of text communications, and using either of those across the board would remove the ambiguity around usage of "channel" in the Meshtastic context.

**Comment by garthvh** [comment]
Lora channel is being changed to frequency slot.

**Comment by tekstrand** [comment]
Hey @garthvh is the PR in for that change in the apps yet? Let us know when we're close there and we'll get the docs going.

**Comment by RubyMetro** [comment]
> Lora channel is being changed to frequency slot.

I think LoRa channel should stay the same because it makes sense for that option to be called that, but by changing the name of talk channels it might help new users to understand initial setup of their devices a little better

**Comment by asjmcguire** [comment]
I would like to chime in here - typically a "channel" is considered by non technical people at least, to be a one way thing - like a TV channel, a Telegram channel, a WhatsApp channel - they are usually a one to many broadcast mechanism, that does not have the facility for the many to reply back.

channel is really only a two way thing, in the CB / HAM world.

I put my vote behind group / topic / room.

**Comment by garthvh** [comment]
> Hey @garthvh is the PR in for that change in the apps yet? Let us know when we're close there and we'll get the docs going.

It is updated on iOS, I opened an issue here for the docs https://github.com/meshtastic/meshtastic/issues/1017
