### ISSUE TITLE
Clarify that serial is disabled when device is in sleep mode

### ISSUE THREAD

**Issue by nagumii** [meshtastic/meshtastic#1055]
Currently, it is unclear on the Device page that ROUTER involves sleep mode, and that sleep mode disables serial output.

Suggested fix: add the following to the serial output section: "Devices utilizing "sleep" to save power will have unreliable serial output, as it is disabled when the device enters sleep. For ROUTER role, consider switching to ROUTER_CLIENT."

**Comment by tekstrand** [comment]
I saw someone in my local mesh having issues with this same issue yesterday, a few others spoke up saying they had run into the same thing, but did not know why. This explains it.

I do wonder whether "Serial disabled in sleep mode" is truly the core issue here, or if it's a lack of knowledge that Router goes in to sleep mode at all. None of my local mesh(including myself) was aware of that. And I am the one who wrote the most recent version of the device roles!

**Comment by nagumii** [comment]
It needs to be clarified, absolutely.

**Comment by tekstrand** [comment]
FAQ is a great idea, I hadn't thought of that.

I think the serial module section makes sense, I also wonder if adding something to the power section makes sense. One problem I've noticed we have on the docs is that some pages have **lots** of admonitions which actually makes them more difficult to digest, in my opinion. If we do want to add something to the power page, I think it would be worth considering if we can reduce overall admonitions on that page.

For the device role page, are you picturing an admonition that is something like this? Or something different?
```
### {DEVICE ROLES WITH POWER SAVING
These device roles enable power saving features which may...
```

**Comment by tekstrand** [comment]
One thing that might help is adding headings to admonitions, which is what I was suggesting above with that code block.

**Comment by nagumii** [comment]
Adding to the faq is good, but there needs to be something on the device
config page imho. People won't think to look at the faq. Maybe just a
parenthetical or footnote?

**Comment by tekstrand** [comment]
@nagumii we're suggesting "both and" not "either or" here.

>Ohhh. I didn't realize that sorry... Does that work though?

I think so. If nothing else, we can change the title of the admonition like it is set here for the power calc
https://meshtastic.org/docs/configuration/radio/power/#calibration-process-attribution

**Comment by nagumii** [comment]
Ah, missed that. Whoops. Carry on 👍

**Comment by tekstrand** [comment]
Originally I was thinking this, but I like the other way much better

<img width="894" alt="Screenshot 2024-03-01 at 11 15 13 AM" src="https://github.com/meshtastic/meshtastic/assets/5215365/4876b26f-38b8-41ed-b5d2-b63424ae5aff">

**Comment by tekstrand** [comment]
As a "test run" for cleaning up admonitions, I opened a PR which cleans up the Power page. I think this will help us decide what to do here on this issue.
https://github.com/meshtastic/meshtastic/pull/1069

**Comment by tekstrand** [comment]
Okay, I gave it a shot. Let me know what y'all think on the PR.

**Comment by tekstrand** [comment]
Thank you for your help on this @rcarteraz and @nagumii !
