### ISSUE TITLE
Add to Tips Documentation

### ISSUE THREAD

**Issue by pdxlocations** [meshtastic/meshtastic#1111]
A great collection of tips to reduce mesh traffic from:
https://discord.com/channels/867578229534359593/871553024030556250/1201242481438752768
"Try to limit all periodic broadcasts intervals (especially https://meshtastic.org/docs/configuration/module/telemetry#device-metrics-update-interval and position). If you need to increase hops, only do it on nodes at the edges, not the ones in the middle. MQTT is generally not advised when you're duty cycle restricted, because the gateway node is then doing all the work."

**Comment by GUVWAF** [comment]
I was referring to MQTT _downlink_ (on active public channels) here. _Uplink_ only for map reporting or sensory data does not affect LoRa transmissions.
