### ISSUE TITLE
Discrepancy Regarding Paxcounter Module

### ISSUE THREAD

**Issue by moabits** [meshtastic/meshtastic#1188]
**Describe what section of the docs is outdated or otherwise in need of change**

[Documentation](https://meshtastic.org/docs/configuration/module/paxcounter/) states: "To operate the Paxcounter Module, it is mandatory to **switch _off_** both WiFi and Bluetooth in your Network and Bluetooth settings."
[iOS app](https://github.com/meshtastic/meshtastic/assets/45351488/7b6405f4-0867-40b8-b3ec-63dbfbe87225) says: "Both WiFi and Bluetooth must be **enabled** for PAX counter to work."

**Suggested Changes**

Please update _either_ the docs or the description in the app to clear up the confusion.
Does WiFi and Bluetooth have to be Enabled or Disabled in the app's settings for the Paxcounter Module to work?

**Comment by pdxlocations** [comment]
Hmm, I had to turn them off to get the module to work.  @garthvh ?

**Comment by caveman99** [comment]
BLE and Wifi need to be turned OFF for paxcounter to work, cause it takes over the radio of the ESP32.

**Comment by garthvh** [comment]
No idea, I will go with @caveman99

**Comment by pdxlocations** [comment]
Website documentation is correct
