### ISSUE TITLE
Protocol endiannes missing

### ISSUE THREAD

**Issue by mrx23dot** [meshtastic/Meshtastic#1221]
https://meshtastic.org/docs/overview/mesh-algo/
doesn't say little/big endian fur multi bytes

also a link to implementation file would be nice.

**Comment by pdxlocations** [comment]
I am not proficient with encryption techniques, could you expand on your request?

**Comment by pdxlocations** [comment]
@mrx23dot, thank you for the clarification, perhaps @GUVWAF would be able to comment?

**Comment by GUVWAF** [comment]
The PacketHeader is a struct allocated on ESP32/nRF52/RP2040, which are all using little-endian.

This page is not meant as a reference for a compatible implementation, the source code is linked on several places in the documentation. The specific place is likely to be changed in the future, but here's the PacketHeader at this point in time: https://github.com/meshtastic/firmware/blob/d4d89447bd417895b32e9a264bb76a22065b577f/src/mesh/RadioInterface.h#L46

**Comment by pdxlocations** [comment]
@mrx23dot based on this information, do you have a proposed change for the documentation or shall we close this issue?

**Comment by pdxlocations** [comment]
@mrx23dot Would you want to add the information using the "Edit this page" link on the bottom of every docs page?
