### ISSUE TITLE
Debounce Up/Down/Select  in canned messages to prevent skipping entries

### ISSUE THREAD

**Issue by lupusworax** [meshtastic/meshtastic#1240]
When going through the list of canned messages up/ down mostly skips a entry when letting the button go. Very rarely it works. it probably needs a debounce set to prevent it from happening.

**Comment by pdxlocations** [comment]
Hi @lupusworax , thanks for the report, however this is the meshtastic documentation/website repo.  You may wish to open a an issue in https://github.com/meshtastic/firmware
