### ISSUE TITLE
Deprecate Router_Client

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic#1328]
Router_Client will be deprecated with the next release (meshtastic/firmware/pull/4201), docs will need to be updated to reflect this.

**Comment by Talie5in** [comment]
Reading through the issue thread and the PR.

I suggest perhaps breaking it down to simpler terms in the docs.

Router for Permanent Infrastructure (noting no WiFi, MQTT, Store and Forward functions will be enabled/enable-able)
Client for non-Mobile Nodes that connect to services over WiFi/Ethernet such as MQTT, and ability to enable features such as Store and Forward.
Client_Mute for Mobile devices but same features as Client.
