### ISSUE TITLE
Document new public MQTT server restrictions

### ISSUE THREAD

**Issue by GUVWAF** [meshtastic/meshtastic#1384]
It would be good to document the new restrictions of the public MQTT server on the website as well, to avoid issues like https://github.com/meshtastic/firmware/issues/4500 

Basically this information:

> Important: These changes only affect users using the default PSK (Pre-Shared Key).
> 
> Here's what you need to know:
> 
> 1️⃣ Zero-Hop Policy:
>    • MQTT tests won't populate to your local Mesh. 
> 
> 2️⃣ Optimized to Focus on Most Important Traffic:
>    • NodeinfoApp
>    • TextMessageCompressedApp
>    • TextMessageApp
>    • PositionApp
>    • TelemetryApp
>    • MapReportApp
>    • RoutingApp

**Comment by pdxlocations** [comment]
added in #1545
