### ISSUE TITLE
GPS display enhancements

### ISSUE THREAD

**Issue by snake0073** [meshtastic/Meshtastic#139]
1. It would be nice to have an option to change the GPS elevation format similar to the GPS location format. 
Options like Feet MSL, Meters MSL, Feet HAE, Meters HAE, etc.

2. When the device has no on-board GPS (i.e. Heltec LoRa32), it does not show it's own position on the on-device display's GPS page, only "NO GPS UNIT". Recommend, when the unit has no on-board GPS, but is getting valid location data from the paired phone, have the location display on the device's display.

3. In-app option for setting GPS position and altitude format for all devices on the mesh on the user list.

**Comment by sachaw** [comment]
Hi, I can see this issue relates to a number of products [Firmware](https://github.com/meshtastic/meshtastic-device) and [Android](https://github.com/meshtastic/meshtastic-android). could you please open the issues in the respective repo's, Thanks.
