### ISSUE TITLE
[Documentation Change Request]: Wrong topic for Home Assistant sensor value templates

### ISSUE THREAD

**Issue by riker09** [meshtastic/meshtastic#1598]
### Request Details

Hello. I'm not sure if it is a bug in the documentation or a misunderstanding how Meshtastic works on my end, so please be kind. I _think_ there is an error in the examples for the Temperature, Humidity and Pressure templates in the HA documentation in `docs/software/integrations/mqtt/home-assistant.mdx`.

I have tried to get a sensor node talk to my other node which acts as an MQTT gateway to my Mosquitto broker. I have copied the examples but only `Battery Voltage`, `Battery Percent`, `ChUtil` and `AirUtilTX` were showing values in my HA.

In the example the topic for all template sensors is the same: `msh/US/2/json/LongFast/!67ea9400`. After I switched that to `msh/US/2/json/PKI/!67ea9400` the sensor values started appearing in HA. A more detailed research is available in another ticket: https://github.com/meshtastic/firmware/issues/5139

It would be super helpful if the official documentation would explain how the MQTT topic is build on the gateway node. It was (and is) unclear to me what happens when I set a different topic. As far as I understand it parts of it are still built in a dynamic way?

Here's what i have in mind:

`msh/{CHANNEL}/2/json/PKI/{NODE_ID}`

`CHANNEL` and `NODE_ID` seem obvious to me. But what is `2`, `json` and `PKI`? Is there another format besides `json` that the node could emit?

Sorry that this Change Request is rather a request for clarification. If this is the wrong channel to make such a request I apologize and would welcome any pointer into the right direction. You may close this request in such a case, of course.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
PKI are encrypted direct messages, home assistant is using the JSON topic as they are not encrypted

**Comment by ianmcorvidae** [comment]
You're getting these on the PKI topic when you're requesting them from the CLI, looks like -- this is expected, as the telemetry packets aren't sent on channels when being sent as a response to a request like this. Any regularly scheduled broadcasts you have set up in the telemetry module settings will be sent on whatever your primary channel is, however (so LongFast unless you've configured something different).

If you'd like the topic to pick up messages whether they're sent via PKI direct messages or via channel messages, try a topic like: `msh/US/2/json/+/!67ea9400` (`+` is an MQTT topic wildcard that matches within a block delimited by slashes). I'm unsure if this belongs in the docs or not -- most of the time people are wanting to pick up the regularly scheduled stuff and aren't doing active requesting or anything.

Your breakdown of the topic isn't quite right either. The setup is: `<root topic>/<major version>/<minor version OR json>/<channel name OR PKI>/<uplinking node ID>` -- so in your case, `msh/US` would be what's in your root topic in MQTT settings (probably default if you're in the US); 2 is the current major version; you're using JSON but the other messages are probably coming through on the `e` area; regular messages on `LongFast` or DMs on `PKI` (unless you have other stuff) and your gateway node ID is `!67ea9400`

**Comment by riker09** [comment]
Thanks for the explanation. Indeed this was a misunderstanding from reading the documentation on my part. I still think that your answer may be helpful to others, especially this part:

> The setup is: <root topic>/<major version>/<minor version OR json>/<channel name OR PKI>/<uplinking node ID>

I will close this issue now.
