### ISSUE TITLE
Help!!!  Canned Message Module Disabled

### ISSUE THREAD

**Issue by Dogsrearwheels** [meshtastic/meshtastic#1625]
Hi I am a newbie to the project, I have connected a rotary encoder, checked the wiring, checked the settings, umpteen times, still the message ‘canned message module disabled’ even though enabled in app? And the rotary encoder does nothing. Can anybody help?![image](https://github.com/user-attachments/assets/20a6d380-1c87-4b99-bd3d-0721fe25f009)![image](https://github.com/user-attachments/assets/132ed508-d25a-49c5-9f18-a64cb9178953)

**Comment by tekstrand** [comment]
Hi @Dogsrearwheels - I think you'll find more support by posting in Discord or on Reddit. The GitHub issues for this are specifically for updates or inaccuracies related to the documentation system
