### ISSUE TITLE
MQTT broker connection keeps dropping

### ISSUE THREAD

**Issue by brianshea2** [meshtastic/meshtastic#1633]
Hello! I maintain the map over at MeshMap.net.

For the past couple days or so, I've noticed the MQTT connection to the public broker work as expected for some seconds, then go silent, then my MQTT client reports no ping response and disconnects. It then reconnects and repeats, cycling every few minutes or so.

Anything going on over there? :)

**Comment by thebentern** [comment]
Thanks for the report. Seeing some high CPU usage. I am rebooting the instance now.

**Comment by brianshea2** [comment]
Seems to be fixed.

**Comment by tekstrand** [comment]
Thanks for the heads up, @brianshea2 !

**Comment by brianshea2** [comment]
Appears to be having issues again
