### ISSUE TITLE
Integrate info from wiki pages

### ISSUE THREAD

**Issue by sachaw** [meshtastic/Meshtastic#17]
Theres still some pages with good info on @ https://github.com/meshtastic/Meshtastic-device/wiki
Once it's done, I can remove it

**Comment by jfirwin** [comment]
I'll work on this next week with @apt105 and I think we can make some serious headway.

**Comment by qurm** [comment]
Hi,  I wrote the guide on the Android app wiki here:
[](https://github.com/meshtastic/Meshtastic-Android/wiki/User-Guide-for-Meshtastic-Android-App)

I'd like to move it over and update anything that needs it, and any style changes.  I still have the images on my own github repo, so should move those too.  Do we have a clear location for them?  I create a PR?

**Comment by sachaw** [comment]
Just look in sidebar.js, you will see the correct location for it, feel free to submit a PR.

**Comment by apt105** [comment]
I essentially did a copy and paste of that at the weekend. See https://github.com/meshtastic/Meshtastic/pull/29

Please let me know if you want to change it at all, it could do with proof reading!

**Comment by qurm** [comment]
Great - will review it soon!

**Comment by mkinney** [comment]
Can we close this issue?

**Comment by sachaw** [comment]
Yep! I'll remove the wiki and close this now
