### ISSUE TITLE
Check links which points to vercel.app

### ISSUE THREAD

**Issue by fabaff** [meshtastic/Meshtastic#242]
**Describe what section of the docs is outdated or otherwise in need of change**

Link which point to Vercel are 404.

E.g., https://meshtastic-python.vercel.app/meshtastic/index.html

**Suggested Changes**
Check the Vercel setup or update the links to the current location.

**Additional Notes**
Add any other context here.

**Comment by jfirwin** [comment]
Sorry for the slow response here.

I'll check and see what those are supposed to link to. I *think* they should be pointing to https://python.meshtastic.org.

I found two instances of the vercel version of the link. [Here](https://github.com/meshtastic/Meshtastic/blob/a9bf30549334a7943a18c4c0a5f72e587c8a6192/docs/software/python/development.md?plain=1#L112) and [here](https://github.com/meshtastic/Meshtastic/blob/a9bf30549334a7943a18c4c0a5f72e587c8a6192/docs/software/python/installation.md?plain=1#L11)
