### ISSUE TITLE
Documentation Change Request

### ISSUE THREAD

**Issue by prampec** [meshtastic/meshtastic#271]
**Section in need of change**
Hardware

**Suggested Changes**
While hardware page is already very useful, there is no compare page can be found in the web to highlight differences. Maybe Meshtastic community could solve this issue, and help to decide which device to purchase.

Also, there can be a some Meshtastic oriented suggestions for the specific hardware. See example below.

**Additional Notes**
_Example1_: LillyGo TTGO v1.0 does not provide a battery level measurement, but you can add that externally by connecting GPIO35 to both GND and Battery input via same value (10K?) resistors. And mark this new feature in variants/tlora_v1/variant.h by adding line `#define BATTERY_PIN 35`

_Example2_: I personally discovered, that LillyGo TTGO v1.0 has a quite week charging circuit, but are other devices are any better in that?

_Example3_: External notification module has hints on which pin to use on specific devices.

_Example4_: different LoRa chips are utilized in the boards, but what differences can we expect?

**Comment by jfirwin** [comment]
This is something that is being worked on. I think I should make the spreadsheet available for input. We've been putting together a central location for all device specifications as well as how well certain features work with Meshtastic. It's a definite work in progress, but it may pick up some speed if we crowdsource some of the information gathering.
