### ISSUE TITLE
Typo on instructions page

### ISSUE THREAD

**Issue by raldi** [meshtastic/Meshtastic#276]
https://meshtastic.org/docs/getting-started/flashing-firmware says, "If you have already downloaded/installed the MacOS WCH-IC CH340 ("CH341SER_MAC") drivers via the CH34x_Install_V1.5.pkg, you will have to Uninstall the kernel extension" and the command it gives is`sudo -rf /Library/Extensions/usbserial.kext`, but there's supposed to be an `rm` in there.

**Comment by andrekir** [comment]
thanks for reporting. I'll fix that in a bit.
