### ISSUE TITLE
Documentation Change Request - Broken link on LilyGo Lora page

### ISSUE THREAD

**Issue by fabfurnari** [meshtastic/Meshtastic#377]
**Describe what section of the docs is outdated or otherwise in need of change**

The LILYGO LORA page has a broken link (the warning about potentially hazardous boards)

**Suggested Changes**

As the linked page is no longer available I suggest using the Internet Archive one: 
 https://web.archive.org/web/20220613134559/https://www.thethingsnetwork.org/community/berlin/post/warning-attention-users-of-ttgo21-v16-boards-labeled-t3_v16-on-pcb-battery-exploded-and-got-on-fire

**Comment by garthvh** [comment]
Link has been removed
