### ISSUE TITLE
iOS App Does Not Always Notify on New Message

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic#395]
Using an ESP32 LoRa module with 1.3.39 alpha on it and the latest iOS app, when the phone screen is off and a message is received, it does appear on the screen on the ESP32, however it does not always appear in the app.  Device section still shows device is connected (via Bluetooth). Closing and restarting the iOS app does then show the last message.

**Comment by garthvh** [comment]
Please file iOS bugs via TestFlight so I have the stack trace, I suspect your device does not show properly subscribed.
