### ISSUE TITLE
UI Overlapping on node info screen when no position info present.

### ISSUE THREAD

**Issue by JiimBob** [meshtastic/Meshtastic#448]
When you select a node on the Nodes tab, if the device doesn't have a position set the icons for the short name, device type, SNR and plug status overlap with the title bar.
![Example screenshot](https://user-images.githubusercontent.com/44332255/197363298-0cb383db-794b-4896-8766-549349f6742e.png)

**Comment by garthvh** [comment]
Please use TestFlight to report iOS bugs

**Comment by garthvh** [comment]
This is also in the 1.2 version of the app which will expire soon
