### ISSUE TITLE
Update docs to explain the need to chain commands 

### ISSUE THREAD

**Issue by garthvh** [meshtastic/meshtastic#453]
Now that all of the config sections and modules reboot when they are saved the CLI documentation needs to be updated to recommend chaining commands together by module.

There are also some edge cases that need documentation, any of the fixed position values (alt, lat, long) will reboot because they also save the fixed_position value in postion.config so they need to be chained together as well

**Comment by charlesmarseille** [comment]
Good point, also for people who type fast, sending commands while the node is rebooting can result in missed settings changes. chaining fixes this situation.
