### ISSUE TITLE
Document all button click behavior

### ISSUE THREAD

**Issue by thebentern** [meshtastic/meshtastic#456]
Not sure if we go for unified page or section in an existing area, or if we make this hardware specific but we need to document what all of the user button click behaviors do. The problem is that specific devices like the T-Beam and T-Echo have different sets of additional buttons and button behaviors.

**Comment by jfirwin** [comment]
Thanks @sigmahour I'm marking this as closed by #499

**Comment by garthvh** [comment]
Those details are not correct, the BLE and AP functions are gone and there is a new triple click to send a position.

**Comment by jfirwin** [comment]
@garthvh nice catch. Thanks for the clarifications. Still getting my 2.0 bearings I guess 🙂

**Comment by sachaw** [comment]
I'd change it to hardware buttons instead of LoRa buttons, as they don't have anything to do with LoRa directly

**Comment by sachaw** [comment]
Yeah, but hardware buttons will be obvious for even the most inept users, as they will have the context of the device anyway

**Comment by sachaw** [comment]
But either way is fine

**Comment by sachaw** [comment]
Can we close this as complete now?
