### ISSUE TITLE
Code Block copy button does not work in Safari

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/meshtastic#545]
When using the copy button in code blocks while using Safari as my browser, nothing gets copied. Works fine using Chrome/Edge though.

**Comment by jfirwin** [comment]
I know! This one is such a pain for MacOS. I looked at it and couldn't figure it out... didn't know where to look honestly.

**Comment by sachaw** [comment]
Out of our hands, maybe try filing the issue with Docusaurus directly
