### ISSUE TITLE
"Learn More" CTA is confusing to new users

### ISSUE THREAD

**Issue by ajmcquilkin** [meshtastic/meshtastic#562]
## Overview

As a new user, I was thrown off by the "Learn More" call-to-action button on the [meshtastic.org](https://meshtastic.org/) homepage (see first image below) bringing me to what appeared to be incomplete technical documentation (see second image below). I would have expected this link to immediately bring me to a more introductory page where I could learn more about the project (i.e., the [Introduction](https://meshtastic.org/docs/introduction) page).

I can understand why the "Learn More" button would bring users to a page that links to the important pages shown in the second image below, but I would argue the following:

1. New users are the most likely to click the "Learn More" button of all users, as more experienced users can quickly access the same links from the "About" dropdown menu currently on the homepage (third image below). I would argue that new users are exceedingly likely to be expecting an "Introduction" page when "learning more" as opposed to the other listed pages.
2. Due to the nature of the Meshtastic docs, the "Introduction" page appears above the "Overview," "Contributing," and "FAQ" pages within the left-side site sidebar (see fourth image below). Because of this, these pages feel like logical next pages to read after reading the "Introduction" page.
3. Expanding on point 2, the "Introduction" page explicitly links to the "Overview" page after the user has finished reading (see fifth image below).

As such, I would argue for the "Learn More" link on the homepage to link to the [Introduction](https://meshtastic.org/docs/introduction) page instead of the [About](https://meshtastic.org/docs/about) page.

**Edit:** The "Docs" link on the homepage currently points to the "Introduction" page. This "Docs" link could be changed to point to the "About" page, which is the first page of documentation.

## Images

![image](https://user-images.githubusercontent.com/46639306/211841573-46adcd5e-e314-4f49-affc-0048998763a1.png)
*1. CTA Button on homepage*

![image](https://user-images.githubusercontent.com/46639306/211841862-9ee20c02-d1fc-4600-a4d8-bec980f15f3c.png)
*2. Linked page from homepage "Learn More" button*

![image](https://user-images.githubusercontent.com/46639306/211843643-5a758a13-64d4-4999-b3d4-28b516eec7da.png)
*3. Existing "About" menu on homepage*

![image](https://user-images.githubusercontent.com/46639306/211844727-9752c8ec-2dc5-4bef-89a5-7c418e357ffc.png)
*4. Existing page navigation clearly showing all relevant pages*

![image](https://user-images.githubusercontent.com/46639306/211845577-8d23cdcb-d6ce-44ec-8d89-27e43aea030d.png)
*5. "Introduction" page linking to "Overview" page*

**Comment by jfirwin** [comment]
You found a relic! Back when I added the CTA the website looked like [this](https://meshtastic-f0si341nh-jfirwin.vercel.app) and the docs/about page had content. Some time later we switched to the auto generated sidebars and that created all of these pages with the big blocky buttons for the directories. I'll take a look at the PR but I think this sounds look a good plan currently. As @rcarteraz mentioned, there's work being done on a new about page. Though my bandwidth is limited currently.
