### ISSUE TITLE
Wifi password including !! is parsed as bang bang

### ISSUE THREAD

**Issue by ss32** [meshtastic/meshtastic#592]
When passing a password that includes !!, the string is parsed as a ["bang bang"](https://stackoverflow.com/questions/15137461/what-exactly-is-sudo-bang-bang)  in the bash shell, resulting in the previous command being used as the password instead of just passing the raw !! string.

```
$ ls
$ meshtastic --set network.wifi_psk ThisWontWork!!
meshtastic --set network.wifi_psk ThisWontWorkls
Connected to radio
Set network.wifi_psk to ThisWontWorkls
Writing modified preferences to device
```

**Comment by mc-hamster** [comment]
closing issue.

please use whatever escaping your shell supports.
