### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by redfang790** [meshtastic/meshtastic#673]
there is this one browser on github that you can get internet over text at https://github.com/lukeaschenbrenner/TxtNet-Browser I'm just wondering if you would like to try to get something like that on meshtastic so we can have internet over lora using meshtastic

**Comment by garthvh** [comment]
Meshtastic does not use sms at all, so some sort of bridge would be required.

**Comment by garthvh** [comment]
You would have to have internet. meshtastic uses Lora p2p so there are no gateways.

**Comment by charminULTRA** [comment]
@redfang790 Have you looked into the MQTT features? On a sidenote, LoRa is super, super low bandwidth.

**Comment by garthvh** [comment]
> @charminULTRA look at this https://github.com/dmahony/LoRa-AX25-IP-Network

That looks like a better choice if you want do do tcp over Lora
