### ISSUE TITLE
Some material inaccurate or missings steps

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [meshtastic/Meshtastic#69]
I've been running through the material and have used trial/error and played around with some of these commands to get them to work. There are many things that may be out of date as well. Is there anyone maintaining this site? If not, I'm unable to make pull requests for meshtastic.org. I'd like to be able to contribute if I can.

Let me know what I can do and I can make contributions to this as well :)

Thanks!

**Comment by sachaw** [comment]
There are maintainers, however the scope of the docs extends far beyond general use.

PR's are very welcome.
