### ISSUE TITLE
https://meshtastic.org/tools/OEM crashes with o.mQ.toBinary is not a function

### ISSUE THREAD

**Issue by Kollensperger** [meshtastic/meshtastic#705]
https://meshtastic.org/tools/OEM used to work, now it crashes on safari, google chrome with the following error:

`o.mQ.toBinary is not a function. (In 'o.mQ.toBinary({oemAesKey:t,oemFont:l,oemIconBits:m,oemIconHeight:g,oemIconWidth:h,oemText:b})', 'o.mQ.toBinary' is undefined)`

**Comment by pdxlocations** [comment]
Looks like it's fixed
