### ISSUE TITLE
Wrong purchase link for T-Echo

### ISSUE THREAD

**Issue by TheDoctorT** [meshtastic/Meshtastic#74]
The current purchase link leads to the store page of the SoftRF version. It should be updated with the link to the page of the Meshtastic version: https://m.aliexpress.com/item/1005003026107533.html

**Comment by garthvh** [comment]
Created a pull request

https://github.com/meshtastic/Meshtastic/pull/79

**Comment by KrazyKerbalnaut** [comment]
This should be closed at this time.

**Comment by TheDoctorT** [comment]
Sorry, first time I open an issue. Didn't realize it was up to me to close. Thank you for the comment :)

**Comment by sachaw** [comment]
Pro tip: If you include "Closes #123" in the pr title where 123 is the issue you opened, it will auto-close when it's merged

**Comment by TheDoctorT** [comment]
Thank you sachaw, great tip
