### ISSUE TITLE
Silicon Labs Removed Their UART Driver Download

### ISSUE THREAD

**Issue by lifenouveau** [meshtastic/meshtastic#800]
https://github.com/meshtastic/meshtastic/blob/7929fde2903720dabfeab5375611cf9cd701f0aa/docs/getting-started/serial-drivers/serial-drivers-esp32.mdx#L14

**Did they pull their driver download?**

The download link for Windows 10 appears to be missing. On the legacy OS page on their site, the download links no longer work. 
Internet Archive links still work.

**Comment by lifenouveau** [comment]
Empty downloads section on Chrome.
![image](https://github.com/meshtastic/meshtastic/assets/1139009/e2edba11-8b89-479a-aac1-8bf58184692a)

**Comment by pdxlocations** [comment]
I emailed Silicon Labs and they've restored the downloads.
