### ISSUE TITLE
Outdated hardware pages

### ISSUE THREAD

**Issue by sachaw** [meshtastic/Meshtastic#83]
Issue to bring docs into alignment with current hardware availability and instructions.

Anyone please feel free to add any clarity points or issues you have experienced and we can address them here.

**Comment by sachaw** [comment]
@KrazyKerbalnaut can't  assign you yet, once you get a few more contributions on the repo, I'll be able to.

**Comment by KrazyKerbalnaut** [comment]
Sounds good. I'm planning on writing a hardware page for Project Hydra too when we get to a public release.

**Comment by garthvh** [comment]
I updated the RAK page with what I know works right now.
