### ISSUE TITLE
Documentation Change Request

### ISSUE THREAD

**Issue by Reid-n0rc** [meshtastic/meshtastic#847]
Please - if you just have a question, post in our [forum](https://meshtastic.discourse.group) instead. Please reserve this system for requesting changes to the Meshtastic documentation.

**Describe what section of the docs is outdated or otherwise in need of change**
Line 146 of faq.mdx https://github.com/meshtastic/meshtastic/blob/21d9fa646b99592b9dc5ba229a7d24b2125f90a5/docs/about/faq.mdx#L146 states that the maximum power is 1500 Watts. Since LoRa is spread spectrum, this should be a maximum power of 10 Watts. This is per [47 CFR 97.313(j)](https://www.ecfr.gov/current/title-47/part-97#p-97.313(j))

**Suggested Changes**
Change Line 146 of faq.mdx to state the maximum power is 10 Watts, not 1500 Watts.

**Additional Notes**
It may be worth noting that this only applies to the United States and laws vary in other countries. 

Also, 10 Watts on LoRa is still insanely high power given its very low SNR threshold.

**Comment by pdxlocations** [comment]
This is not my area of expertise so I asked in the Discord and you are correct.  Would you like to hit that "edit this page" button on the faq page and make the change yourself?

Link to the conversation: https://discord.com/channels/867578229534359593/871540428510474302/1161478629407064184

**Comment by Reid-n0rc** [comment]
@pdxlocations I created PR #848 to change the FAQ. Needs reviewed to have it implemented.

**Comment by Reid-n0rc** [comment]
Fixed with PR #848 being accepted
