### ISSUE TITLE
RTL_433 Support - New Feature

### ISSUE THREAD

**Issue by MiddleSiggy** [meshtastic/meshtastic#874]
Is it possible for you to add the feature to allow for a RTL_433 radio so we can pick up radio signals from remote and send them across the mesh network to the MQTT cloud.

I have 2 cases where I need this:
Case 1) I have a remote weather station I would like to monitor that is currently beyond the range of my Wifi network to be able to pick it up with a Pi or other device, So I would like to set up a Lora network to broadcast the information across the mesh to a MQTT gateway and then bring that into my smart home

Case 2) I have a remote water system, and would like to use the RTL_433 to monitor the water meter in a similar way using the MQTT messaging to keep an eye on the water system to watch for water leaks. It is a remote sprinkler system, but there is nothing around the water meter to be able to get Internet access, so I need a way to send the information via another way to get it to my monitoring system. In this way I can watch for usage and if a leak were to happen send an alert.

Thanks

**Comment by garthvh** [comment]
You can use the serial module to send data from another microcontroller into the mesh, we support SPI Lora radios supported by RadioLib.
