### ISSUE TITLE
CardKB to t-beam

### ISSUE THREAD

**Issue by zonder16** [meshtastic/Meshtastic#88]
Want to add CardKB to t-beam 

[m5 Card KB](http://docs.m5stack.com/en/unit/cardkb?spm=a2g0n.appdesc.0.0.2a9exioCxioCb6&_currency=RUB&_lang=ru_RU&fromApp=true&statusBarHeight=63&_dognoseId=WVM4MGZoWHZtZzREQUVhMHAvNHlIYnYBfRiDFfBhbGlleHByZQAAANkm)

**Comment by sachaw** [comment]
There is discussion on discord about adding support for hardware like this on discord, please bring this up there, or feel free to open an issue and pr if you wish to contribute something.
